import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const formatDistance = (distanceMeters) => {
    if (distanceMeters === null) {
        return "-";
    }
    if (distanceMeters < 1000) {
        return `${Math.max(1, Math.round(distanceMeters))} m`;
    }
    return `${(distanceMeters / 1000).toFixed(1)} km`;
};
export const LiveNavigationCard = ({ hasRoute, navigationActive, permissionState, gpsError, currentInstruction, nextInstruction, remainingDistanceKm, remainingDurationMinutes, speedKmh, distanceToInstructionMeters, offRoute, rerouting, focusModeActive, onStart, onStop, onToggleFocusMode }) => {
    return (_jsxs("section", { className: "card nav-card", "aria-live": "polite", children: [_jsxs("div", { className: "nav-card-header", children: [_jsxs("div", { children: [_jsx("p", { className: "result-label", children: "Rijmodus" }), _jsx("h3", { children: navigationActive ? "Live navigatie actief" : "Klaar om te navigeren" })] }), navigationActive ? (_jsxs("div", { className: "nav-card-actions", children: [_jsx("button", { type: "button", className: "ghost", onClick: onToggleFocusMode, children: focusModeActive ? "Verlaat focus" : "Open focusmodus" }), _jsx("button", { type: "button", className: "ghost", onClick: onStop, children: "Stop navigatie" })] })) : (_jsx("button", { type: "button", onClick: onStart, disabled: !hasRoute, children: "Start navigatie" }))] }), !hasRoute && _jsx("p", { className: "muted", children: "Bereken eerst een route voordat je live navigatie start." }), permissionState === "unsupported" && _jsx("p", { className: "nav-alert", children: "Deze browser ondersteunt geen geolocatie." }), permissionState === "denied" && _jsx("p", { className: "nav-alert", children: "Locatietoegang geweigerd. Sta GPS-toegang toe om te navigeren." }), gpsError && _jsx("p", { className: "nav-alert", children: gpsError }), rerouting && _jsx("p", { className: "nav-chip", children: "Je wijkt van route af. Nieuwe route wordt berekend..." }), offRoute && !rerouting && navigationActive && _jsx("p", { className: "nav-chip nav-chip-warning", children: "Je bent van de route afgeweken." }), navigationActive && currentInstruction && (_jsxs("div", { className: "nav-instruction", children: [_jsx("p", { className: "result-label", children: "Volgende instructie" }), _jsx("h2", { children: currentInstruction.instruction }), _jsxs("p", { className: "muted", children: ["Over ", formatDistance(distanceToInstructionMeters)] })] })), navigationActive && (_jsxs("div", { className: "nav-stats-grid", children: [_jsxs("div", { children: [_jsx("p", { children: "Resterende afstand" }), _jsx("strong", { children: remainingDistanceKm !== null ? `${remainingDistanceKm.toFixed(1)} km` : "-" })] }), _jsxs("div", { children: [_jsx("p", { children: "Resterende tijd" }), _jsx("strong", { children: remainingDurationMinutes !== null ? `${Math.max(0, Math.round(remainingDurationMinutes))} min` : "-" })] }), _jsxs("div", { children: [_jsx("p", { children: "Snelheid" }), _jsx("strong", { children: speedKmh !== null ? `${Math.max(0, Math.round(speedKmh))} km/u` : "-" })] })] })), navigationActive && nextInstruction && (_jsxs("p", { className: "muted nav-next", children: ["Daarna: ", nextInstruction.instruction] }))] }));
};
